/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.infox.telas;

import javax.swing.JOptionPane;

/**
 *
 * @author Nine
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        lblUsuario = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Desktop = new javax.swing.JTextArea();
        Menu = new javax.swing.JMenuBar();
        Mencadcli = new javax.swing.JMenu();
        MencadUsu = new javax.swing.JMenuItem();
        mencadCli = new javax.swing.JMenuItem();
        Mencadurl = new javax.swing.JMenu();
        menop = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        jDesktopPane1.setBackground(new java.awt.Color(204, 255, 255));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 304, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 309, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Comentarios");
        setBackground(new java.awt.Color(255, 204, 204));

        lblUsuario.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblUsuario.setText("Usuario");

        Desktop.setBackground(new java.awt.Color(204, 204, 255));
        Desktop.setColumns(20);
        Desktop.setRows(5);
        jScrollPane1.setViewportView(Desktop);

        Mencadcli.setText("Cadastrar");
        Mencadcli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MencadcliActionPerformed(evt);
            }
        });

        MencadUsu.setText("Comentario");
        MencadUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MencadUsuActionPerformed(evt);
            }
        });
        Mencadcli.add(MencadUsu);

        mencadCli.setText("Usuario");
        mencadCli.setEnabled(false);
        mencadCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mencadCliActionPerformed(evt);
            }
        });
        Mencadcli.add(mencadCli);

        Menu.add(Mencadcli);

        Mencadurl.setText("Comentario");
        Mencadurl.setEnabled(false);
        Menu.add(Mencadurl);

        menop.setText("Opções");
        menop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menopActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Sair");
        menop.add(jMenuItem1);

        Menu.add(menop);

        setJMenuBar(Menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblUsuario)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUsuario))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(444, 369));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menopActionPerformed
        // exibe caixa de dialogo
        int sair = JOptionPane.showConfirmDialog(null,"Tem certeza que deseja sair?","Atenção",JOptionPane.YES_NO_OPTION);

        if (sair == JOptionPane.YES_OPTION){
        System.exit(0);
    }
    }//GEN-LAST:event_menopActionPerformed

    private void mencadCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mencadCliActionPerformed
    //abaixo para abrir a tela desktop pane 
       TelaUsuario cliente =
       desktop.add(cliente);       
        
        
    }//GEN-LAST:event_mencadCliActionPerformed

    private void MencadUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MencadUsuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MencadUsuActionPerformed

    private void MencadcliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MencadcliActionPerformed
        //chamando a tela comentario
        TelaComentario comentario = new TelaComentario();
        comentario.setVisible(true);
        Desktop.add(comentario);
    }//GEN-LAST:event_MencadcliActionPerformed
             
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Desktop;
    private javax.swing.JMenuItem MencadUsu;
    private javax.swing.JMenu Mencadcli;
    public static javax.swing.JMenu Mencadurl;
    private javax.swing.JMenuBar Menu;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JLabel lblUsuario;
    public static javax.swing.JMenuItem mencadCli;
    private javax.swing.JMenu menop;
    // End of variables declaration//GEN-END:variables
}
